# Jekyll configuration

name: ColdNigt Blog
# 변경
description: about I
# 변경
meta_description: "Your New Jekyll Site, Blogging about stuffs"
# 변경
markdown: kramdown
# kramdown: markdown의 개조판.
# markdown에서 불편한 사항을 개선한 형태.

highlighter: rouge
# 원래 Pygments
# text highlighter로 rouge 이용
# 2016. 02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

logo: false
paginate: 10
# 작성한 모든 post를 하나의 페이지에 열거할 수 없으니
# pagination이 필요하고 몇개의 post를 하나의 page에서 보여줄 건지를 설정.

language: 'en-uk'
# 언어 설정

baseurl: /
domain_name: 'http://yourblog-domain.com'
# 변경

google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: https://ColdNight-Zero.github.io
author: ColdNight